name: 'publish'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'write'
      pull-requests: 'read'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-node@v3'
        with:
          node-version: 18

      - uses: 'denoland/setup-deno@v1'
        with:
          deno-version: 'v1.x'

      - name: 'Get Version'
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: 'Build Package'
        run: 'deno task build'

      - uses: 'JS-DevTools/npm-publish@v2'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: './cache'
      
      - name: 'Publish Release'
        uses: 'azurystudio/log@v1'
